-- MySQL Script generated by MySQL Workbench
-- Sun Feb 11 12:19:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 24769562_robert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 24769562_robert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `24769562_robert` DEFAULT CHARACTER SET latin2 ;
USE `24769562_robert` ;

-- -----------------------------------------------------
-- Table `24769562_robert`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`car` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `colour` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `engine_size` FLOAT NULL DEFAULT NULL,
  `engine_power` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `24769562_robert`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`customers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `24769562_robert`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers_idx` (`customer` ASC),
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customer`)
    REFERENCES `24769562_robert`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `24769562_robert`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `order` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_fk_idx` (`order` ASC),
  CONSTRAINT `order_fk`
    FOREIGN KEY (`order`)
    REFERENCES `24769562_robert`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `24769562_robert`.`vin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`vin` (
  `id` INT UNSIGNED NOT NULL,
  `vin` VARCHAR(17) NULL,
  `id_vin` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_car_UNIQUE` (`id` ASC),
  UNIQUE INDEX `id_car_UNIQUE` (`id_vin` ASC),
  CONSTRAINT `id_vin_fk`
    FOREIGN KEY (`id_vin`)
    REFERENCES `24769562_robert`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_robert`.`tires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_robert`.`tires` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tires_type` VARCHAR(45) NULL,
  `id_tires` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_tires_fk_idx` (`id_tires` ASC),
  CONSTRAINT `id_tires_fk`
    FOREIGN KEY (`id_tires`)
    REFERENCES `24769562_robert`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
